[lang]
name = "Deutsch"

[inanima]
app.title = "Inanima"
settings.settings = "Einstellungen"
settings.theme.label = "Designmodus"
settings.theme.system = "System"
settings.theme.light = "Hell"
settings.theme.dark = "Dunkel"
settings.language.label = "Sprache"
loading.initializing = "Anwendung wird initialisiert..."
loading.fonts = "Schriftarten werden geladen..."
loading.languages = "Sprachdateien werden geladen..."
loading.database = "Verbindung zur Datenbank..."
loading.finishing = "Fertigstellung..."
download.title = "Sprachdatei herunterladen"
download.downloading = "Herunterladen"
download.speed = "Geschwindigkeit"
download.remaining = "Verbleibend"
download.calculating = "Berechnung..."
download.cancel = "Abbrechen"
download.success = "Download abgeschlossen"
download.failed = "Download fehlgeschlagen"
download.close = "Schließen"
